// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // สำหรับ Prisma Migrate (ใช้ Direct Connection)
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
    // สำหรับ Prisma Client (ใช้ Connection Pooling)
    // จะถูกส่งผ่าน PrismaClient constructor
  },
});
